version: '3.4'

networks:
  # The presence of these objects is sufficient to define them
  registry-net: {}

services:

  CollectorRegistry.RabbitMQ:
    image: rabbitmq:3-management-alpine
    ports: 
      - "15672:15672"
    hostname: rabbit01
    networks: 
      - registry-net

  collectorregistry.server:
    image: ${DOCKER_REGISTRY-}collectorregistryserver
    hostname: web01
    networks: 
      - registry-net
    build:
      context: .
      dockerfile: CollectorRegistry/Server/Dockerfile

  collectorregistry.geocodeservice:
    image: ${DOCKER_REGISTRY-}collectorregistrygeocodeservice
    networks: 
      - registry-net
    build:
      context: .
      dockerfile: CollectorRegistry.GeocodeService/Dockerfile


  #collectorregistry.testconsole:
  #  image: ${DOCKER_REGISTRY-}collectorregistrytestconsole
  #  build:
  #    context: .
  #    dockerfile: CollectorRegistry.TestConsole/Dockerfile

  collectorregistry.geocodetestinput:
    image: ${DOCKER_REGISTRY-}collectorregistrygeocodetestinput
    networks: 
      - registry-net
    build:
      context: .
      dockerfile: CollectorRegistry.GeocodeTestInput/Dockerfile



  collectorregistry.databridge:
    image: ${DOCKER_REGISTRY-}collectorregistrydatabridge
    networks: 
      - registry-net
    build:
      context: .
      dockerfile: CollectorRegistry.DataBridge/Dockerfile

