version: '3.4'
name: CollectorRegistry

networks:
  default:
    name: registry-net

services:

  #CollectorRegistry.RabbitMQ:
  #  image: rabbitmq:3-management-alpine
  #  ports: 
  #    - "127.0.0.1:15672:15672"
  #  hostname: rabbit01

  collectorregistry.server:
    image: ${DOCKER_REGISTRY-}collectorregistryserver
    hostname: web01
    build:
      context: .
      dockerfile: CollectorRegistry/Server/Dockerfile

  collectorregistry.geocodeservice:
    image: ${DOCKER_REGISTRY-}collectorregistrygeocodeservice
    build:
      context: .
      dockerfile: CollectorRegistry.GeocodeService/Dockerfile


  collectorregistry.testconsole:
    image: ${DOCKER_REGISTRY-}collectorregistrytestconsole
    build:
      context: .
      dockerfile: CollectorRegistry.TestConsole/Dockerfile

  collectorregistry.geocodetestinput:
    image: ${DOCKER_REGISTRY-}collectorregistrygeocodetestinput
    build:
      context: .
      dockerfile: CollectorRegistry.GeocodeTestInput/Dockerfile



  collectorregistry.databridge:
    image: ${DOCKER_REGISTRY-}collectorregistrydatabridge
    build:
      context: .
      dockerfile: CollectorRegistry.DataBridge/Dockerfile

